/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/
        
/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.domino;

import lotus.domino.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.mule.api.ConnectionExceptionCode;
import org.mule.api.annotations.*;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.display.Password;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.ConnectionException;
import org.mule.modules.domino.util.TransformUtil;

import java.util.Map;

/**
 * Cloud Connector
 *
 * @author Arbuz LLC.
 */
@Connector(name="domino", schemaVersion="1.0-SNAPSHOT", description = "Domino Integration", friendlyName = "Domino",
           connectivityTesting = ConnectivityTesting.DISABLED)
public class DominoConnector
{

    protected transient Log logger = LogFactory.getLog(getClass());

    private Session session;
    private Database database;

    private String sessionToken;


    /**
     * Configurable
     */
    @Configurable
    private String serverName;

    /**
     * Configurable
     */
    @Configurable
    private String databaseName;

    /**
     * Configurable
     */
    @Configurable
    private String host;

    /**
     * Configurable
     */
    @Configurable
    private String port;

    /**
     * Connect
     *
     * @param username A username
     * @param password A password
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey String username, @Password String password)
        throws ConnectionException {

        try {
            session  = NotesFactory.createSession(host + ":" + port, username, password);
            database = session.getDatabase(serverName, databaseName);

            sessionToken = session.hashCode() + "";
        } catch(NotesException ne) {
            ne.printStackTrace();
            throw new ConnectionException(ConnectionExceptionCode.UNKNOWN, null, ne.getMessage(), ne);
        }
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() throws Exception {
        /*
         * CODE FOR CLOSING A CONNECTION GOES HERE
         */
        if (database != null)
            database.recycle();
        if (session != null)
            session.recycle();
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        return session != null && database != null;
    }

    /**
     * Connection identifier
     */
    @ConnectionIdentifier
    public String connectionId() {
        return sessionToken;
    }

    /**
     * Invokes read method on Domino database
     *
     * {@sample.xml ../../../doc/Domino-connector.xml.sample domino:read}
     *
     * @param unid Content to be processed
     * @return Domino Document
     * @throws NotesException when document can not be found
     */
    @Processor
    public Document read(String unid) throws NotesException
    {
        logger.trace("read");
        Document document = database.getDocumentByUNID(unid);

        return document;
    }

    /**
     * Invokes create method on Domino database
     *
     * {@sample.xml ../../../doc/Domino-connector.xml.sample domino:create}
     *
     * @param payload Payload to be processed
     * @return Universal ID
     * @throws NotesException when document can not be found
     */
    @Processor
    public String create(Map payload) throws NotesException
    {
        logger.trace("create");
        Document document = database.createDocument();

        TransformUtil.mapToDocument(database, payload, document);

        if (document.save())
            return document.getUniversalID();
        else
            return null;
    }

    /**
     * Set server name property
     *
     * @param serverName Server name
     */
    public void setServerName(String serverName)
    {
        this.serverName = serverName;
    }

    public String getServerName(){
        return this.serverName;
    }

    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * Set database name property
     *
     * @param databaseName Server name
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
    }

    public String getHost() {
        return host;
    }

    /**
     * Set host property
     *
     * @param host host
     */
    public void setHost(String host) {
        this.host = host;
    }

    public String getPort() {
        return port;
    }

    /**
     * Set port property
     *
     * @param port host
     */
    public void setPort(String port) {
        this.port = port;
    }

}
