/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.domino;

import org.mule.module.client.MuleClient;
import org.mule.tck.junit4.FunctionalTestCase;

public abstract class AbstractDominoFunctionalTestCase extends FunctionalTestCase
{

    protected MuleClient client;

    @Override
    protected void doSetUp() throws Exception
    {
        super.doSetUp();
        client = new MuleClient(muleContext);
    }

}